default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  host: localhost
  database: clean_app_dev
  username: laurajaime
  password: password
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_TEST_DATABASE'] %>

integration:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
