:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", "5").to_i %>
:queues:
  - [active_storage_analysis, 2]
  - [active_storage_purge, 2]
  - [block_user, 2]
  - [close_meeting_reminder, 1]
  - [conference_diplomas, 2]
  - [decidim_events, 2]
  - [default, 2]
  - [events, 2]
  - [exports, 1]
  - [invite_participants, 4]
  - [mailers, 4]
  - [metrics, 1]
  - [newsletter, 2]
  - [newsletters_opt_in, 2]
  - [reminders, 2]
  - [translations, 2]
  - [user_report, 2]
  - [vote_reminder, 2]